### ISSUE TITLE
Missing dependency when installing TU Ilmenau's fork on Eclipse 2019-12

### ISSUE THREAD

**Issue by allentiak** [ObeoNetwork/UML-Designer#1058]
Hi, @AlexanderWichmann 

Great that you revived this great project!

As I could not open an issue in your fork, I did it here.

I've just tried to install your package from your update site on Eclipse 2019-12, with no avail. There seems to be a missign dependency upstream...

Details below.

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: UML Designer 9.0.0.202001020505 (org.obeonetwork.dsl.uml2.runtime.feature.feature.group 9.0.0.202001020505)
  Missing requirement: Dashboard 9.0.0.201901300933 (org.obeonetwork.dsl.uml2.dashboard 9.0.0.201901300933) requires 'osgi.bundle; org.eclipse.amalgam.explorer.activity.ui 0.0.0' but it could not be found
  Missing requirement: Dashboard 9.0.0.202001020505 (org.obeonetwork.dsl.uml2.dashboard 9.0.0.202001020505) requires 'osgi.bundle; org.eclipse.amalgam.explorer.activity.ui [1.8.0,2.0.0)' but it could not be found
  Cannot satisfy dependency:
    From: UML Designer 9.0.0.202001020505 (org.obeonetwork.dsl.uml2.design 9.0.0.202001020505)
    To: osgi.bundle; org.obeonetwork.dsl.uml2.dashboard [9.0.0,10.0.0)
  Cannot satisfy dependency:
    From: UML Designer 9.0.0.202001020505 (org.obeonetwork.dsl.uml2.runtime.feature.feature.group 9.0.0.202001020505)
    To: org.eclipse.equinox.p2.iu; org.obeonetwork.dsl.uml2.design [9.0.0.202001020505,9.0.0.202001020505]
```

**Comment by AlexanderWichmann** [comment]
Hi @allentiak ,

We are pleased that you are interested in our fork.

We are aware of the problem. Eclipse has removed the third-party plugin 'org.eclipse.amalgam.explorer.activity' from its update site so that it can no longer be found during installation. Thus, you have to add another update-site providing this plugin/ feature like [https://download.eclipse.org/modeling/amalgam/updates/stable/1.9.2-S20181203/capella/](https://download.eclipse.org/modeling/amalgam/updates/stable/1.9.2-S20181203/capella/)

See also here: [https://github.com/ObeoNetwork/UML-Designer/issues/1030](https://github.com/ObeoNetwork/UML-Designer/issues/1030)

I will adapt our description accordingly. Thank you very much.

Best Regards

Btw, I enabled the issue option in our fork (was just disabled by default).

**Comment by allentiak** [comment]
See also #1057

**Comment by allentiak** [comment]
@AlexanderWichmann Thanks for the pointer! I added the update site and I could install the package :-)
