### ISSUE TITLE
Labels show "Invalid feature as name"

### ISSUE THREAD

**Issue by marcham** [ObeoNetwork/UML-Designer#389]
UML Designer 2.4.1
The Import metaclass or stereotype elements show on the diagram with label "Invalid feature as name".

**Comment by Pontesegger** [comment]
Can see this error with Eclipse Mars when using an enumeration type as property datatype
![diagram_editor_bug](https://cloud.githubusercontent.com/assets/2060477/8429894/40e0f520-1f2c-11e5-89db-c21f472c30c0.png)

**Comment by Pontesegger** [comment]
sorry, last comment was about the ecore diagram editor

**Comment by cbrun** [comment]
Hi Christian, this has been reported already and fixed in EcoreTools, see : https://bugs.eclipse.org/bugs/show_bug.cgi?id=470959

The updated build can be picked up in the nightly maintenance builds or through the "Install more modeling components" if you are using the Modeling package. Here is the update-site (works for Mars too and not only luna)
 
http://download.eclipse.org/ecoretools/updates/nightly/3.0.x/luna
