### ISSUE TITLE
Investigate use of UMLResourcesUtil.init(ResourceSet)

### ISSUE THREAD

**Issue by cbrun** [ObeoNetwork/UML-Designer#417]
The class org.eclipse.uml2.uml.resources.util.UMLResourcesUtil.init(ResourceSet) is supposed to prepare a ResourceSet to make sure UML models pathmaps & friends are correctly initialized.

This might be usefull for UML Designer though I am not sure it is necessary.

This change made in EcoreTools is similar of how it could be done :
http://git.eclipse.org/c/ecoretools/org.eclipse.ecoretools.git/commit/?id=a0fc4320545f9a6e6791e828750d528947fb9f61

**Comment by AxelRICHARD** [comment]
Fix has been proposed https://github.com/ObeoNetwork/UML-Designer/pull/938 but not sure it will help because UMLResourcesUtil.init
Initializes the registries for the specified resource set (and/or the
global registries) with the registrations needed to work with UML2
resources in stand-alone mode (i.e., without Eclipse).
