### ISSUE TITLE
Support qualifiers on association ends.

### ISSUE THREAD

**Issue by pietermartin** [ObeoNetwork/UML-Designer#434]
Qualifiers are indispensible in modelling accurate class diagrams.

**Comment by mbats** [comment]
See spec UML 2.5:
* page 168 A_qualifier_associationEnd [Association]
* 11.5.3 Semantis: "A qualified Association end has qualifiers that partition the instances associated with an instance at that end, the qualified instance. Each partition is designated by a qualifier value, which is a tuple comprising one value for each qualifier . The multiplicities at the other ends of the association determine the number of instances in each partition. So, for example, 0..1 means there is at most one instance per qualifier value. If the lower bounds are non-zero, the qualifier values must be a finite set, for example because the qualifiers are typed by enumerations."
* 11.5.4 Notation: "A qualifier is shown as a small rectangle attached to the end of an association path between the final path segment and the symbol of the Classifier that it connects to. The qualifier rectangle should be smaller than the attached class rectangle, unless this is not practical. The qualifier rectangle is part of the association path, not part of the Classifier. The qualifier rectangle is attached to the end of the association path that represents the memberEnd that owns the qualifier. 
The multiplicity attached to the target end denotes the possible cardinalities of the set of target instances selected by the pairing of a qualified instance and a qualifier value.
The qualifier attributes are drawn within the qualifier box. There may be one or more attributes, shown one to a line. Qualifier attributes have the same notation as Classifier attributes, except that initial value expressions are not meaningful. It is permissible (although somewhat rare), to have a qualifier on every end of a single association.
A qualifier may not be suppressed."
* 11.5.5 Examples: Figure 11.37

**Comment by pietermartin** [comment]
Great stuff, I'll download and have a look. Thanks
