### ISSUE TITLE
[Sys2Soft/4.2] When creating a diagram from a model element, one should be able to choose content to be initialized

### ISSUE THREAD

**Issue by zmanzelji-tas** [ObeoNetwork/UML-Designer#577]
At the creation of a diagram on a model element, it would be convenient to have a window poping up, showing a tree with the element's children to be selected and added to the diagram at its initialization

**Comment by mbats** [comment]
The first idea was to open automatically the wizard associated to the Add tool in the palette. But as Sirius does not provide any simple api to do that we implemented another solution as it was done in EcoreTools. When a diagram is empty, an text is displayed to explain to the user how to important elements in an empty diagram. The idea is to add a double click action on this text in order to import automatically all the direct chlidren of the current root diagram element.

So now to initialize an empty diagram, it is possible to: 
* use the add tool from the palette
* drag & drop elements from the model explorer
* use the add related elements pop up menu
* double click on the text to import the direct children
