### ISSUE TITLE
Review the labels on transitions

### ISSUE THREAD

**Issue by mbats** [ObeoNetwork/UML-Designer#864]
The labels on the transitions are not anymore visible.

**Comment by fbats** [comment]
Transition labels are computed as described in the UML 2.5 specification : chapter 14.2.4.9 
[<trigger> [‘,’ <trigger>]* [‘[‘ <guard>’]’] [‘/’ <behavior-expression>]]

In order to be less ambiguous the field "Name" in property views have to be removed.
It have to be done when properties view will be Re-implemented using the new Sirius

**Comment by mbats** [comment]
It works fine now.
